### ISSUE TITLE
Union null/bytes with from_value

### ISSUE THREAD

**Issue by mlh758** [flavray/avro-rs#108]
I have a field of type: ` "name": "value","type": ["null", "bytes"]` as part of a record. avro-rs decodes the record fine, and if I do a `println!` I see the value as `("value", Union(Bytes([8, 128, 144, 194, 193, 24...`

However, it's not clear to me how this can then be consumed. It seems like:
`let data: Option<Vec<u8>> = from_value(rec).unwrap();`
would be the way to go since the union is null or an array of bytes but I get `Error { message: "not an array" }` when I try to convert it.

The documentation only covers more straightforward types and the unit tests seem to interact with the Value types instead. I'd be happy to open a PR with more documentation if anyone is able to help.

**Comment by poros** [comment]
I am afraid there is a bug with the serde deserealization of bytes. With the following tests:
```
    #[test]
    fn test_bytes_simple() -> Result<(), Error> {

        let raw_schema = r#"
        {
            "type": "bytes"
        }
        "#;

        let schema = Schema::parse_str(raw_schema)?;
        let mut writer = Writer::with_codec(&schema, Vec::new(), Codec::Deflate);
        let bytes: &[u8] = &[1u8, 2u8];
        writer.append(bytes)?;
        writer.flush()?;
        let input = writer.into_inner();
        let reader = Reader::with_schema(&schema, &input[..])?;
        for value in reader {
            let v = value?;
            println!("{:?}", v);
            println!("{:?}", from_value::<Vec<u8>>(&v).unwrap());
        }
        Ok(())
     }

    #[test]
    fn test_bytes_field() -> Result<(), Error> {

        #[derive(Debug, Serialize, Deserialize)]
        struct Test {
            c: Vec<u8>,
        }

        let raw_schema = r#"
        {
            "type": "record",
            "name": "test",
            "fields": [
                {"name": "a",  "type": "bytes"}
            ]
        }
        "#;

        let schema = Schema::parse_str(raw_schema)?;
        let mut writer = Writer::with_codec(&schema, Vec::new(), Codec::Deflate);
        let bytes: &[u8] = &[1u8, 2u8];
        let mut record = Record::new(writer.schema()).unwrap();
        record.put("a", bytes);
        writer.append(record)?;
        writer.flush()?;
        let input = writer.into_inner();
        let reader = Reader::with_schema(&schema, &input[..])?;
        for record in reader {
            let r = record?;
            println!("{:?}", r);
            println!("{:?}", from_value::<Test>(&r).unwrap());
        }
        Ok(())
     }

    #[test]
    fn test_union_bytes_field() -> Result<(), Error> {

        #[derive(Debug, Serialize, Deserialize)]
        struct Test {
            c: Option<Vec<u8>>,
        }

        let raw_schema = r#"
        {
            "type": "record",
            "name": "test",
            "fields": [
                {"name": "a",  "type": ["null", "bytes"]}
            ]
        }
        "#;

        let schema = Schema::parse_str(raw_schema)?;
        let mut writer = Writer::with_codec(&schema, Vec::new(), Codec::Deflate);
        let bytes: &[u8] = &[1u8, 2u8];
        let mut record = Record::new(writer.schema()).unwrap();
        record.put("a", Some(bytes));
        writer.append(record)?;
        writer.flush()?;
        let input = writer.into_inner();
        let reader = Reader::with_schema(&schema, &input[..])?;
        for record in reader {
            let r = record?;
            println!("{:?}", r);
            println!("{:?}", from_value::<Test>(&r).unwrap());
        }
        Ok(())
     }
```

I get:
```
failures:

---- tests::test_bytes_simple stdout ----
Bytes([1, 2])
thread 'tests::test_bytes_simple' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "not an array" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- tests::test_bytes stdout ----
Record([("a", Bytes([1, 2]))])
thread 'tests::test_bytes' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "incorrect value" }', src/libcore/result.rs:1188:5

---- tests::test_union_bytes stdout ----
Record([("a", Union(Bytes([1, 2])))])
thread 'tests::test_union_bytes' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "incorrect value" }', src/libcore/result.rs:1188:5
```

I suspect that we are seeing two different bugs.

In case of the record field, deserializing of bytes gets forwarded to [deserialize_any](https://github.com/flavray/avro-rs/blob/3417ccd2dc11b0bf419d426998551808a91ab191/src/de.rs#L114) instead of [deserialize_bytes](https://github.com/flavray/avro-rs/blob/3417ccd2dc11b0bf419d426998551808a91ab191/src/de.rs#L152) or [deserialize_byte_buf](https://github.com/flavray/avro-rs/blob/3417ccd2dc11b0bf419d426998551808a91ab191/src/de.rs#L163).

In case of the simple bytes type, deserializing of bytes invokes [deserialize_seq](https://github.com/flavray/avro-rs/blob/3417ccd2dc11b0bf419d426998551808a91ab191/src/de.rs#L219), but not being an actual avro `Array` type, the deserialization goes into the error branch.

For both of those, I don't have a super-quick fix in mind, unfortunately :disappointed: 

As a note, I have noted that we only implement `ToAvro` for [&'a[u8]](https://github.com/flavray/avro-rs/blob/183893ef8b9ae76cb6ea8492767c4a81c5b95d6d/src/types.rs#L113), while we could also implement it for `Vec<u8>` in case users wants to serialize starting directly from that.

**Comment by mlh758** [comment]
> As a note, I have noted that we only implement ToAvro for &'a[u8], while we could also implement it for Vec<u8> in case users wants to serialize starting directly from that.

I can't speak for other users on this one, I my use case was all about reading a bunch of existing Avro records.

I've only been a consumer of serde code up to this point so I would have to do some research before I could make any comments on how to help. I was hoping I was just using the library wrong. For the moment I've switched to a Python library and probably won't be able to contribute back on this if I'm not consuming it.

I appreciate you taking the time to answer though. In a way this resolves my issue, I'll leave it up to you on whether to close it or leave it open as a sort of documentation for other users.

**Comment by cpcloud** [comment]
This isn't a bug in `avro-rs`'s `Deserializer` implementation, it's a known limitation in serde: https://github.com/serde-rs/serde/issues/518. In the meantime, you can use the wrapper types in [`serde_bytes`](https://github.com/serde-rs/bytes) (`Bytes`, `ByteBuf`) to force a call to `(de)serialize_bytes`/`(de)serialize_byte_buf`. You can also slap a `serde(with = "serde_bytes")` on a field to ser/deser with those methods as well.

Perhaps avro-rs should have some documentation (maybe even a test or two) to let users know how they can use bytes effectively with avro-rs and serde.

**Comment by poros** [comment]
Ah, good to know! I could not really find a way to fix it! Thanks @cpcloud .

I'll leave this one open until we have a couple tests and we update the docs.

**Comment by mlh758** [comment]
I had some free time to mess with this again. Using serde_bytes did the trick and I was able to read a message into my struct. An example in the docs or a unit test demonstrating this would be great but I'm happy to have something working.
