### ISSUE TITLE
Move to thiserror for errors

### ISSUE THREAD

**Issue by cpcloud** [flavray/avro-rs#115]
`failure` is leaking into the public API and forcing downstream consumers to either `Box` up the failure error or depend on `failure` if they want to explicitly handle the error.

Moreover, error types do not have any precise information in the type about what went wrong. `thiserror` would allow us to provide very specific error variants, as well as avoiding leaking types into the public API and letting downstream consumers handle the variants as they wish.

**Comment by poros** [comment]
I have used failures too much to like it, but at the same time I became kinda skeptical of any new rust error-handling library :/
At a first glance it looks like to be a good one, but before embarking in such a big change, maybe I would wait to see if the Rust community converges on something ;)

**Comment by cpcloud** [comment]
The main issues here IMO are the inability for dependents to get more specific error messages, and leaking the failure dependency if you don't want to box everywhere. The convenience of error reporting the way its currently done in avro rs is really for applications, whereas library errors should be as specific and efficient as possible.

**Comment by athre0z** [comment]
FWIW, failure is now officially deprecated:
https://github.com/rust-lang-nursery/failure/pull/347

With all new error handling libs being built around `std::error::Error`, it's not insanely important what library the community converges towards. Whether you use `thiserror` or any other of the new libs, other than with failure, the errors can just be converted into a common `Box<dyn std::error::Error>`.

**Comment by cpcloud** [comment]
The specific library doesn't matter. What matters is the way that errors are presented to dependents IMO. The way in which `failure` is used in `avro-rs` precludes dependents handling errors in a way that is appropriate for their use.

**Comment by poros** [comment]
I have been following a bunch of discussions in the community and it does indeed seem that `anyhow` and `thiserror` don't have a clear path to obsolescence in front of them for now, neither there are other "big" enough players to choose from (mark my words, a new revolutionary crate will be announced the minute after I hit "Comment" 😛 ).

Agreed, let's move to `thiserror` and this time let's make error handling right, as @cpcloud pointed it out.
