### ISSUE TITLE
Batching & Compression[HELP + INFO Request]

### ISSUE THREAD

**Issue by amrx101** [flavray/avro-rs#128]
I would like to know what is the recommended practice for `Writer` with a `Codec`. If say we have a thousand items of a particular record, are we suppose to `append_ser` each record iteratively rather than a batch insert? If so when does the compression codec kicks in, upon `flush`?

P.S. Sorry for the trivial question.

**Comment by poros** [comment]
That was actually not a trivial question at all! I had to look back at the code to answer, given that I haven't written the Codec implementation.

Compression indeed happens over the invocation of [`flush`](https://github.com/flavray/avro-rs/blob/5acbfbfbc53a58774a8492a284ebca3a6670d52c/src/writer.rs#L243) over the stream of bytes in the buffer. `flush` gets also called when the [buffer size grows over the block size](https://github.com/flavray/avro-rs/blob/5acbfbfbc53a58774a8492a284ebca3a6670d52c/src/writer.rs#L99), so I believe that doesn't really matter if you append many small records or you batch them, at least from the perspective of when the compression happens.

If you are curious about performances with many small records vs few big ones, we have some benchmarks that cover exactly this case. Maybe you could run them and change them in a way that is more meaningful to your use case?
