### ISSUE TITLE
Add a parser, to enable references to other schema's

### ISSUE THREAD

**Issue by gklijs** [flavray/avro-rs#139]
I'm currently busy on working to the next release of https://crates.io/crates/schema_registry_converter. With the latest confluent platform it has become possible to refer to other schema's. For Java they use a parser from the Avro client, which can takes multiple schema's and combine them.

An example of the use in the Java client can be seen here: 
https://github.com/confluentinc/schema-registry/blob/4b64c9867272258d51212007439616038b0b9f3c/client/src/main/java/io/confluent/kafka/schemaregistry/avro/AvroSchema.java#L59

I wonder if there is another way to support the same kind of thing with avro-rs? For now I think I will try to replace in either the string or the Json format as I don't see a more type safe way.

**Comment by poros** [comment]
I am not familiar with the Confluent platform, but I think that what you would like to see it would need the features tracked in issues #92 and #95 to be implemented. There is a big open PR #99 which was trying to address them, but it never landed and became quite a bit stale now.

Short answer is: not with the current version of the library, I am afraid :(

**Comment by gklijs** [comment]
Thanks for the quick response. It's indeed not Confluent platform specific. And seems like it should be fixed with those issues.

**Comment by gklijs** [comment]
Closing this one, since there are already other related issues. I'm fixing it for now by transforming it with serde_json, and based on the namespace values, replace the Value::String with a reference for a copy of the reference json. https://github.com/gklijs/schema_registry_converter/blob/71cbc305a019e59f7411ea3656c8eb4123daac60/src/avro.rs#L446
