### ISSUE TITLE
Auto-generating schemas? 

### ISSUE THREAD

**Issue by bzm3r** [flavray/avro-rs#149]
I wondering if I am missing an existing solution to auto-generate schemas from Rust structs?

**Comment by poros** [comment]
Hi! The library doesn't have such a feature, neither I know of nay crate that offers it (there is one that does the opposite afaik)

**Comment by bzm3r** [comment]
Thanks! I have been working today on a simple (very bare bones, geared towards my use case) proc_macro based schema generator. Once I am done, would you be interested in reviewing it and suggesting improvements?

**Comment by poros** [comment]
Perhaps I can give it a look? No promises, though. I don't have much time to dedicate to open source these days and at least I'd like to keep this library in shape.

**Comment by clojurians-org** [comment]
the js avro library has already offer this function:
```
https://github.com/mtth/avsc

https://github.com/mtth/avsc/wiki/Advanced-usage#type-inference
```

**Comment by clojurians-org** [comment]
it seem this function can be done with two library combation .
the first one generate json schema from serde, the second can convert json schema to avro schema.

https://github.com/GREsau/schemars
https://github.com/mozilla/jsonschema-transpiler

**Comment by 0xcaff** [comment]
@poros What's the library which goes the other way (Avro schema to rust structs)?

**Comment by 0xcaff** [comment]
I think this is a duplicate of https://github.com/flavray/avro-rs/issues/62

**Comment by poros** [comment]
Closing as duplicate of #62
