### ISSUE TITLE
Upgrade to latest libflate

### ISSUE THREAD

**Issue by JohnEmhoff** [flavray/avro-rs#150]
Hello! Would you consider upgrading to the latest libflate? The version currently pinned in cargo.toml has a nasty bug in it that causes it to panic on just the wrong input data, which we're hitting all the time: https://github.com/sile/libflate/issues/52 https://github.com/sile/libflate/pull/53

**Comment by poros** [comment]
That sounds like a very reasonable request, @JohnEmhoff . If the latest version is backward-compatible, I can do it now. If it isn't, a PR would be very welcome.

**Comment by poros** [comment]
The change will go out in the next release (hopefully soon, I wanted to include one pending PR)

**Comment by JohnEmhoff** [comment]
Thanks so much! I'm glad it was a straightforward upgrade.
