### ISSUE TITLE
Error caused by using `matches`

### ISSUE THREAD

**Issue by Kalomidin** [flavray/avro-rs#166]
https://github.com/flavray/avro-rs/blob/de6153ecea6fe660bcf20ff67f47a0b05211b8e1/src/schema.rs#L134
In that line, comma causing me build in error:
`SchemaKind::String, | ^ no rules expected this token in macro call avro_rs`

However, when I switched to version `0.11.0`, it was working fine since it is using following matching:

```
impl SchemaKind {
    pub fn is_primitive(self) -> bool {
        match self {
            SchemaKind::Null
            | SchemaKind::Boolean
            | SchemaKind::Int
            | SchemaKind::Long
            | SchemaKind::Double
            | SchemaKind::Float
            | SchemaKind::Bytes
            | SchemaKind::String => true,
            _ => false,
        }
    }
}
```
I was just wondering, whether it is better to switch to the previous implementation that is version `0.11.0`?

**Comment by poros** [comment]
The error will disappear if you update your rust version. Is it something that you can do?

**Comment by Kalomidin** [comment]
@poros thank you for your response.
It solved the issue for me.
I will close the issue.
