### ISSUE TITLE
Rethink the Writer support - Add DatumWriter

### ISSUE THREAD

**Issue by flavray** [flavray/avro-rs#17]
Pretty much like both the Python and Java Avro client libraries do, it would be nice to rethink the way data is written and encoded.

The current `Writer` implementation is limited, and we had to add the `SingleWriter` interface to allow single-message writing support. The approach taken by the official Avro clients is really different and it would be nice to align the Rust library with them.

Proposed changes:
- Add a `DatumWriter` interface (or keep the `Writer` name /shrug) that has a `schema` and is able to `write` datum, if the datum is valid according to the schema
- Move header, sync marker, etc... support to another place?

There is already support for encoding data without a schema in [encode.rs](https://github.com/flavray/avro-rs/blob/dev/src/encode.rs#L6), that should be enough to mimic the `Encoder` interface in Java/Python

**Comment by poros** [comment]
Starting
