### ISSUE TITLE
[Announcement/Action Needed] The project is moving to the Apache Software Foundation

### ISSUE THREAD

**Issue by flavray** [flavray/avro-rs#189]
Hello all,

The Apache Software Foundation (ASF) reached out with an interest to kickstart an official Apache Avro implementation for Rust, basing the initial implementation off the avro-rs codebase.
Concretely, for avro-rs, this means that the license will change to the Apache License, and the code will probably be moved to the apache/avro repository. The project will effectively be donated to the ASF.

@poros and myself have already agreed to the donation.
@cpcloud @jaboatman @nlopes (as seasoned committers) and any other contributor to this project: would you mind letting me know (either privately or here), at soon as is convenient for you, if you disagree with the license change?
If not, the ASF would kindly appreciate if you could sign their [ICLA](https://www.apache.org/licenses/icla.pdf) (notify project: Apache Avro) and send it to secretary@apache.org. More than happy to discuss this into more details if needed! 🙂

I believe this is the best course of action for the project. I am not able to dedicate a sufficient portion of my time to maintain the library. I also believe the ASF is in a better position to drive the project forward, making sure progress goes hand in hand with Apache Avro's progress.

**Comment by cpcloud** [comment]
I support this donation! I've already signed the Apache ICLA elsewhere, how do I notify the Avro project?

**Comment by iemejia** [comment]
This is great news. Thanks @flavray for agreeing to do this, special thanks to @poros too!

@cpcloud let me confirm with someone at the ASF if you may need to send an additional ICLA (hopefully not). I will let you know if needed.

**Comment by iemejia** [comment]
Just confirmed @cpcloud that you do NOT need to sign a new ICLA. Thanks !

**Comment by cpcloud** [comment]
> Just confirmed @cpcloud that you do NOT need to sign a new ICLA. Thanks !

Roger that thanks!

**Comment by nlopes** [comment]
I also support this donation.

**Comment by gklijs** [comment]
Great news indeed.

**Comment by flavray** [comment]
The project has now been donated to the ASF and the code moved to the [apache/avro](https://github.com/apache/avro/tree/master/lang/rust] repository. Thank you all for your support!
