### ISSUE TITLE
No support for named type references

### ISSUE THREAD

**Issue by jchia** [flavray/avro-rs#203]
The following schema parses fine with Python Avro but in avro-rs, `Schema::parse_str()` rejects it with `Error: ParsePrimitive("Dec")`:
```
{
    "type": "record",
    "name": "foo",
    "fields": [
        {
            "name": "x",
            "type": {
                "type": "record",
                "name": "Dec",
                "fields": [
                    {
                        "name": "base",
                        "type": "int"
                    },
                    {
                        "name": "exp",
                        "type": "int"
                    }
                ]
            }
        },
        {
            "name": "y",
            "type": "Dec"
        }
    ]
}
```
The part of the Avro spec describing references to named types is here: https://avro.apache.org/docs/current/spec.html#names

**Comment by martin-g** [comment]
Please use the successor of this project: https://github.com/apache/avro/tree/master/lang/rust

**Comment by martin-g** [comment]
See https://github.com/flavray/avro-rs/pull/99#issuecomment-1017195592
