### ISSUE TITLE
Consuming avro messages from kafka

### ISSUE THREAD

**Issue by nmaki** [flavray/avro-rs#30]
It looks like the crate today supports to use case of reading avro data from a file. I think the ability to deserialize messages from kafka would be nice. Is this a use case that would fit into this crate or would it be better served in a standalone crate?

After some research it appears this functionality would end up needing at least a schema registry client in addition to the ability to parse the wire format described [here](https://docs.confluent.io/3.2.0/schema-registry/docs/serializer-formatter.html#wire-format).

**Comment by nmaki** [comment]
Yeah that makes sense.

That function looks to be exactly what I'll need to get started. Thank you!

**Comment by gklijs** [comment]
@nmaki I wasn't aware of this issue, I had a similar wish and created https://github.com/gklijs/schema_registry_converter which handles the schema registry stuff, and uses this library for the avro part.
