### ISSUE TITLE
Improve readme example

### ISSUE THREAD

**Issue by laslowh** [flavray/avro-rs#31]
I notice that in the example provided in the README (and elsewhere), there is there are two serializations done of the Test struct, once with types::Record, and once with a native rust struct that derives Serialize.  Both of those serializations use the same data (a: 27, b:"foo"),  however when I change the data in the second record to:

    let test = Test {
        a: 999,
        b: "bar".to_owned(),
    };

I get this output:

...
Ok(Test { a: 27, b: "foo" })
Ok(Test { a: 27, b: "foo" })

Because I'm new to Rust and Avro, I'm not sure that I'm not doing something wrong. Shouldn't I be getting:

...
Ok(Test { a: 27, b: "foo" })
Ok(Test { a: 999, b: "bar" })

**Comment by flavray** [comment]
Oh wow, thanks for opening the issue, I was able to reproduce it locally.
The issue seems to be that we re-use the initial state of the byte-array for every item have to read. That means the library is reading the first element over and over.

I'll open a PR with a fix, the library should be usable soon!

**Comment by laslowh** [comment]
Now that's a quick response.  Thanks.  Let me know if there's any way I can help, I'm going to work on porting a project of mine to your library.  I'll let you know if I have any other trouble.

**Comment by flavray** [comment]
I've just released the [0.3.0](https://crates.io/crates/avro-rs) version of the crate, this should have fixed the problem.
Let me know if the new version works better 🙂

Thanks in advance for letting us know if you have any other trouble, and don't hesitate to open issues if other parts of the README/documentation are unclear.  Hope the porting of your project will go smoothly!
