### ISSUE TITLE
Code to serialize derived struct is commented out

### ISSUE THREAD

**Issue by laslowh** [flavray/avro-rs#45]
There's code that's commented out in types.rs:

```
impl<S: Serialize> ToAvro for S {
    fn avro(self) -> Value {
        use ser::Serializer;
        self.serialize(&mut Serializer::new()).unwrap()
    }
}
```

This appears to do exactly what I need to do (create an avro-rs Value from a struct that has derived Serialize).   Is there a preferred way to do this, or can this code be un-commented?

**Comment by flavray** [comment]
This code is commented because it won't compile (due to conflicting implementations of `ToAvro` for many types covered by `Serialize`). I spent days trying to make it work, without success.
If you want to have a try, please do 🙂

In the mean time, if you really need to have a struct transformed into a `Value` (I'd be curious to know why, maybe it would help figure out how to solve the issue), I'd suggest doing it "manually":
```rust
impl YourStruct {
  fn avro(self) -> Value {
    use ser::Serializer;
    self.serialize(&mut Serializer::new()).unwrap()
  }
}
```

**Comment by laslowh** [comment]
Yeah, I did try a bit.

My use case is probably a bit esoteric.  I make heavy use of
from_avro_datum() and to_avro_datum() (thanks for providing those!), and
those operate on Values.

Your code looks good, however, compiling that outside the crate would
require making avro_rs::ser::Serializer visible (possibly by adding a "pub"
mod?).  Would that be possible?

graham

**Comment by flavray** [comment]
Oh indeed, my bad 😄

I see your use-case. Instead of making the serializer public, would you want to have a method like:
```rust
pub fn to_avro_datum_ser<S: Serialize>(schema: &Schema, value: S) -> Result<Vec<u8>, Error>;
```

If that would solve your problem, I wouldn't mind adding it and creating a new version of `avro-rs` 🙂

**Comment by laslowh** [comment]
The other option would be to provide the opposite of  [from_value()](https://docs.rs/avro-rs/0.4.1/avro_rs/fn.from_value.html), "to_value()"

**Comment by flavray** [comment]
That is a great idea! 😄
I've opened #45 to add this function
