### ISSUE TITLE
Unsafe code to transmute floats

### ISSUE THREAD

**Issue by portstrom** [flavray/avro-rs#67]
Unsafe code is used to transmute data between floating point numbers and bytes. This is unsafe for a good reason, as it encourages not caring about endianness. Better use the safe methods [f32::from_bits](https://doc.rust-lang.org/std/primitive.f32.html#method.from_bits), [f32::to_bits](https://doc.rust-lang.org/std/primitive.f32.html#method.to_bits), [f64::from_bits](https://doc.rust-lang.org/std/primitive.f64.html#method.from_bits), [f64::to_bits](https://doc.rust-lang.org/std/primitive.f64.html#method.to_bits), [u32::to_le_bytes](https://doc.rust-lang.org/std/primitive.u32.html#method.to_le_bytes), [u32::from_le_bytes](https://doc.rust-lang.org/std/primitive.u32.html#method.from_le_bytes), [u64::from_le_bytes](https://doc.rust-lang.org/std/primitive.u64.html#method.from_le_bytes) and [u64::to_le_bytes](https://doc.rust-lang.org/std/primitive.u64.html#method.to_le_bytes).

https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/decode.rs#L45
https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/decode.rs#L50
https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/encode.rs#L41
https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/encode.rs#L42

**Comment by poros** [comment]
Thanks for reporting this (and the same goes for the other issues)!
It seems actually a pretty easy fix, so it might be good for people who want to start to contribute or who have a little break time dedicated to open-source.

**Comment by cpcloud** [comment]
@poros This issue was addressed in https://github.com/flavray/avro-rs/pull/113 and can be closed.
