### ISSUE TITLE
Errors hold strings

### ISSUE THREAD

**Issue by portstrom** [flavray/avro-rs#72]
All errors hold a string as their contents. Better hold an enum to make it more semantic and to avoid unnecessary memory allocation and string copying, or at least use a `'static str`.
https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/de.rs#L14
https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/ser.rs#L29
https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/schema.rs#L17
https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/util.rs#L18
https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/util.rs#L32

**Comment by poros** [comment]
#82 covers a broader refactor of error handling in the library, so this could be worked on in tandem with that ticket.

**Comment by poros** [comment]
Errors have changed quite a lot since we moved to `thiserror`, but many of them still include strings.
