### ISSUE TITLE
Update readme example to reflect rust 2018 and smooth onboarding.

### ISSUE THREAD

**Issue by ianpurton** [flavray/avro-rs#74]
To make the example on the front page work we say add to your cargo.toml

> [dependencies]
> avro-rs = "^0.6"

Actually I needed to do this.

> [dependencies]
> serde = "1.0"
> serde_derive = "1.0"
> failure = "0.1.5"
> avro-rs = "^0.6"

Then the example code in the readme uses the older rust syntax

    extern crate avro_rs;

    #[macro_use]
    extern crate serde_derive;
    extern crate failure;

    use avro_rs::{Codec, Reader, Schema, Writer, from_value, types::Record};
    use failure::Error;

With rust 2018 we can replace the above with

    use serde_derive::{Deserialize, Serialize};
    use avro_rs::{Codec, Reader, Schema, Writer, from_value, types::Record};
    use failure::Error;

It would also be nice add enums and some other types to the example to show them working.

Thanks.

**Comment by poros** [comment]
Fixed in #78
