### ISSUE TITLE
Error: ParseSchemaError("Unknown type: enum")

### ISSUE THREAD

**Issue by ianpurton** [flavray/avro-rs#75]
I'm not sure of the status of enum, but not working for me with the following example using avro-rs 0.6.5

```rust
use avro_rs::Schema;
use failure::Error;

fn main() -> Result<(), Error> {
    let raw_schema = r#"
        {
            "type": "record",
            "name": "test",
            "fields": [
                {"name": "a", "type": "long", "default": 42},
                {"name": "b", "type": "string"},
                { "type" : "enum",  "name" : "Numbers", "namespace": "data", "symbols" : [ "ONE", "TWO", "THREE", "FOUR" ]}
            ]
        }
    "#;
    let _schema = Schema::parse_str(raw_schema)?;
    Ok(())
}
```

Gives

> Error: ParseSchemaError("Unknown type: enum")

**Comment by RGafiyatullin** [comment]
I'm not totally sure, but it seems to me that it should go as follows:
```rust
let raw_schema = r#"
        {
            "type": "record",
            "name": "test",
            "fields": [
                {"name": "a", "type": "long", "default": 42},
                {"name": "b", "type": "string"},
                {"name": "Numbers", "type": { "type" : "enum",  "name" : "Numbers", "namespace": "data", "symbols" : [ "ONE", "TWO", "THREE", "FOUR" ]}}
            ]
        }
    "#;
```

https://avro.apache.org/docs/current/spec.html#schema_record :

> fields: a JSON array, listing fields (required). Each field is a JSON object with the following attributes:
> ... "name" ... "doc" ... "aliases" ... "default"

So there can be only four valid attributes on the level you mean to define a record-field.

**Comment by ianpurton** [comment]
Closing as it works with the schema specified as above.

**Comment by RGafiyatullin** [comment]
Oh, anytime! :)

**Comment by ianpurton** [comment]
@RGafiyatullin Sorry. I tried your example and it worked for me. Thanks.
