### ISSUE TITLE
Error types

### ISSUE THREAD

**Issue by tekjar** [flavray/avro-rs#82]
Most of the apis are returning failure::Error. How about reexporting it? Or implementing much more concrete errors?

**Comment by poros** [comment]
Fair point. I believe the library has three errors re-exported atm, but we
can definitely add more if needed.

What are the functions that you are using which are returning just a
generic error?

**Comment by tekjar** [comment]
I'm just getting started. Using [schema parse](https://docs.rs/avro-rs/0.6.5/avro_rs/schema/enum.Schema.html#method.parse_str), [writer append](https://docs.rs/avro-rs/0.6.5/avro_rs/struct.Writer.html#method.append) and [writer flush](https://docs.rs/avro-rs/0.6.5/avro_rs/struct.Writer.html#method.flush)

**Comment by poros** [comment]
Ah, I see now. I think I didn't quite understand how to use the failure
crate. Let me pick it up.

**Comment by poros** [comment]
@flavray I guess that if we want to make this better, one way would be to switch to the [Error/ErrorKind pattern](https://boats.gitlab.io/failure/error-errorkind.html).

I went through some of the crates listed on the [serde landing page](https://serde.rs/) and all of them define their own custom errors, like [toml](https://docs.rs/toml/0.5.0/toml/ser/enum.Error.html). We could also do the same and transform them into `enum` with many variants like explained [here](https://boats.gitlab.io/failure/custom-fail.html).

Which one of the options would you go for?

**Comment by rahulravindran0108** [comment]
The enum variant pattern should work. We can use the failure crate to do so - although there is a big argument to go away from that pattern [here](https://github.com/rust-lang-nursery/rust-cookbook/issues/502#issue-387418261). I can take a shot at this and make a PR ?

**Comment by poros** [comment]
I would be OK with the enum approach and I would be very happy to have new
contributors. @flavray must be on-board with the decision, too, though. He
is the lead maintainer and this is a major version bump.

@flavray: waiting on your reply

**Comment by poros** [comment]
#72 proposes an improvement to `String` being used as error content. I believe it makes sense to tackle the two issues together (#72 might actually not make sense after the refactoring anyway)

**Comment by cpcloud** [comment]
@poros I think this can be closed, since you recently landed your PR to move to `thiserror` :tada:

**Comment by poros** [comment]
Ah, right, thanks.
