### ISSUE TITLE
Support logical types

### ISSUE THREAD

**Issue by poros** [flavray/avro-rs#93]
Avro defines a set of special types built on top of regular types called [logical types](https://avro.apache.org/docs/current/spec.html#Logical+Types) which this package doesn't yet support.

There are already some tests to uncomment which cover the issue that have been backported from the official Avro Python package in #18; they can be found grepping for the issue number.

**Comment by poros** [comment]
There is already an old pull request: #63

**Comment by cpcloud** [comment]
@poros Can this issue be closed?

**Comment by poros** [comment]
Oh, I thought it did automatically. Good catch!
